inherit_gem:
  rubocop-shopify: rubocop.yml

AllCops:
  CacheRootDirectory: tmp/rubocop-cache
  UseCache: true

Style/MethodCallWithArgsParentheses:
  IgnoredMethods:
    - require
    - raise
    - assert
    - refute
    - assert_equal
    - refute_equal
    - assert_nil
    - refute_nil
    - assert_kind_of
    - refute_kind_of
    - assert_predicate
    - refute_predicate

Naming/FileName:
  Exclude:
    - lib/github-authentication.rb
