#!/usr/bin/env ruby
# frozen_string_literal: true

require "github_authentication"

begin
  require "active_support"
  require "active_support/cache"
  require "active_support/notifications"
rescue LoadError
  warn("Active Support is required for the credential helper")
  exit(2)
end

case ARGV[0]
when "get"
  description = $stdin.each_line.map { |line| line.split("=", 2).map(&:strip) }.to_h
  org = description.fetch("path", "").split("/").first
  provider = GithubAuthentication.provider(org: org)

  exit_status = GithubAuthentication::GitCredentialHelper.new(
    provider: provider,
    description: description,
  ).handle_get
  exit(exit_status)
when "store"
  # We maintain our own internal storage, so no-op any `store` requests
when nil, ""
  warn("Supported operations: get, store")
  exit(1)
else
  warn("Unknown argument: #{ARGV[0]}")
  exit(1)
end
