name: Tests

on: [push]

jobs:
  ruby-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: [ '2.6' ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Setup timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: UTC
      - name: Lint Ruby
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          bin/rubocop
      - name: Run Ruby tests
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          bin/rake test
        env:
          SUITE: ruby
